spring:
  application:
    name: gateway-service

# routage statique
  cloud:
    gateway:
      routes:
        - id : route1
          uri : http://localhost:8091/
          predicates :
            - Path= /customers/**
        - id : route2
          uri : http://localhost:8092/
          predicates :
            - Path= /accounts/**

#    discovery:
#      enabled: false

server:
  port: 8088

# tiret = tableau dans le format yml
